# Contest: Connect 4

**Release Date:** 16 September 2024

**Due Date:** 23:59, 9 November 2024

# Overview

Connect 4 is a classic two-player strategy game played on a grid comprising 6 rows and 7 columns. Players take turns dropping discs into one of the columns, where each disc falls to the lowest available position within the chosen column. The objective is to be the first player to align four consecutive discs vertically, horizontally, or diagonally. If the board becomes completely filled without any player forming a four-disc alignment, the game results in a tie.

In this contest, you will apply AI/ML techniques to design your own agent for playing Connect 4. You are free to use any AI/ML algorithms and datasets, and can train a machine learning model to improve your agent's performance.

Firstly, you will be playing against some baby agents, then some cleverer agents, and finally participate in the competition among all students! Isn't it exciting to see your agents competing against your friends and classmates? Don't worry if you can't rank high in the competition: the ranking will not play a significant role in the grade. 

Have fun in the Contest!

### Required Files

- contest.py
- utils.py
- simulator.py
- pygame_simulator.py
- game_utils.py
- zero_game.py

### Plagiarism Policy

Please refer to our [Course Policies](https://canvas.nus.edu.sg/courses/62323/pages/course-policies)

### Post-Contest Survey

Your feedback is important to us! After completing Contest, please take a moment to share your thoughts by filling out this [survey](https://coursemology.org/courses/2851/surveys/2393).

### Notes

While it is possible to write and run Python code directly in Jupyter notebook, we recommend that you do this Contest with an IDE using the `.py` file provided. An IDE will make debugging significantly easier.

# Part 1: Game Environment

We provide a basic game environment that enables your agent to interact with the Connect 4 board. In this section, we will walk you through the game environment and the game mechanics of Connect 4, giving you the tools you need to start developing and implementing your own agent.

## 1.0 Introduction to Connect 4

We begin by using the `initialize` function from the `game_utils` module to set up a new Connect Four game board, which is represented as a 2D numpy array. Although some versions of the game allow for custom grid sizes, we will use the default 6x7 configuration, which is the standard for this contest. Our APIs are designed to be similar to those in [Gymnasium](https://gymnasium.farama.org/index.html), drawing inspiration from their approach. We will be using a game environment with the same API to test your agent.

To access the board's dimensions, you can use the `shape` attribute of the `np.array`, which returns a tuple representing the number of rows and columns.

In [1]:
from game_utils import initialize, step, get_valid_col_id

c4_board = initialize()
print(c4_board.shape)

(6, 7)


### 1.0.1 Printing the board

Once the board is initialized using the `initialize` function from the `game_utils` module, you can print the 2D numpy array to visualize the current game state. The board consists of 7 columns and 6 rows, with each empty cell represented by `0`, indicating that no pieces have been placed yet. To display the board, simply use the `print` function on the initialized board array.

We use the following indexing system for the Connect 4 board, where the top row is indexed as the 0th row and the leftmost column is indexed as the 0th column. These indices are referred to as `row_id` and `col_id`, respectively.

|     |  0  |  1  |  2  |  3  |  4  |  5  |  6  |
| --- | --- | --- | --- | --- | --- | --- | --- |
| **0** |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
| **1** |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
| **2** |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
| **3** |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
| **4** |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
| **5** |  0  |  0  |  0  |  0  |  0  |  0  |  0  |

The output mirrors the appearance of the physical Connect 4 game.

In [2]:
print(c4_board)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


### 1.0.2 Making the first move

Connect 4 is a two-player game where Player 1 and Player 2 take turns dropping pieces onto the game board. In our contest and against our agents, your agent will be fairly assigned as either Player 1 or Player 2. We will adhere to the rule that Player 1 always makes the first move.

Your agent can call `get_valid_col_id` to retrieve a list of valid `col_id`s for the current round. As expected, the list of possible actions will consist of all available `col_id`s where a move can be made.

In [3]:
get_valid_col_id(c4_board)

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

Player 1 decides to place a piece in the 2nd column by calling the `step` function. In this case, the `step` function processes Player 1's move (indicated by `player_id=1`) in column 2 (indicated by `col_id=2`) on the Connect Four board represented by `c4_board`. The `in_place=True` argument ensures that the move is applied directly to the existing board (`c4_board`) without creating a new copy. When `in_place=False`, the function returns a new board with the move applied, leaving the original board unchanged. This flexibility allows you to choose whether to modify the current board or work with a copy for additional operations.

In the example below, we execute a game step where Player 1 places a piece in column 2, with the move applied directly to the existing board. As a result, the function updates and returns the current game board state, reflecting Player 1's move.

In [4]:
step(c4_board, col_id=2, player_id=1, in_place=True)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0]])

After this action, we can print the updated state of the board by calling the `print` function on the board object. As expected, Player 1's piece will be placed in the last row in column 2 (`col_id=2`), occupying the bottom row.

In [5]:
print(c4_board)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]]


### 1.0.3 Making valid moves

Here, we stress the importance of ensuring your agent consistently makes valid moves. Below, we outline several common types of invalid moves your agent must avoid (this list is non-exhaustive). If your agent attempts an invalid move, the contest system will randomly select a move on its behalf, potentially resulting in penalties or even disqualification.

Although some of these scenarios are technically impossible in the contest—since your agent only returns the action and the contest system executes it—this knowledge is crucial for understanding the environment, especially when experimenting locally.

#### Valid actions

Eventually, as the board fills up, some actions will become invalid. For instance, if all available spaces in a column are occupied, no more pieces can be placed in that column.

In this example, we simulate a gameplay between Player 1 and Player 2, where both players consecutively place pieces in `col_id=2`.

In [6]:
step(c4_board, col_id=2, player_id=2, in_place=True)
step(c4_board, col_id=2, player_id=1, in_place=True)
step(c4_board, col_id=2, player_id=2, in_place=True)
step(c4_board, col_id=2, player_id=1, in_place=True)
step(c4_board, col_id=2, player_id=2, in_place=True)
print(c4_board)

[[0 0 2 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 1 0 0 0 0]]


Once the column is full, you'll notice that `col_id=2` is no longer part of the list of valid actions, as no more pieces can be placed in that column.

In [7]:
print(get_valid_col_id(c4_board))

[0 1 3 4 5 6]


Once a column is full, any further attempts to place a piece in that column will result in an invalid action. If your agent attempts such an invalid move, a random action will be executed on your agent's behalf.

In [8]:
step(c4_board, col_id=2, player_id=1, in_place=True)

ValueError: Invalid action: column 2 is already full.

### 1.0.4 Interfacing with the Contest

The contest system will initialize your agent by calling the `__init__` function with the assigned `player_id`. During each round of the game, your agent will be invoked via `make_move(state)`, where the current state of the game is provided as input for your agent to decide its move. The `state` is a read-only 2D numpy array representing the game board, where:
- `0` represents an empty cell,
- `1` represents Player 1's piece,
- `2` represents Player 2's piece.

This ensures your agent receives the most up-to-date game state while maintaining immutability of the board.

#### Example - ZeroAgent

In this example, we define a basic agent called `ZeroAgent`, which always selects the 0th column for its move, regardless of the current game state. The agent does not perform any strategic analysis and will always attempt to place a piece in the first column when invoked. It's important to note that this agent may attempt invalid moves if the 0th column is already full, as it does not adapt to the board's condition.

In [9]:
class ZeroAgent(object):
    def __init__(self, player_id=1):
        pass
    def make_move(self, state):
        return 0

We will now demonstrate the flow of the contest using the `ZeroAgent`:

1. The contest initializes both your agent (Player 1) and the opponent's agent (Player 2).
2. The contest sets up the initial game board state.
3. The contest prompts Player 1 to provide its next move.
4. The contest applies Player 1's move to the game board.

The contest will then repeat steps 3 and 4, alternating between Player 1 and Player 2, until the game concludes with either a win or a draw.

In [10]:
# Step 1
agent1 = ZeroAgent(player_id=1) # Yours, Player 1
agent2 = ZeroAgent(player_id=2) # Opponent, Player 2

# Step 2
contest_board = initialize()

# Step 3
p1_board = contest_board.view()
p1_board.flags.writeable = False
move1 = agent1.make_move(p1_board)

# Step 4
step(contest_board, col_id=move1, player_id=1, in_place=True)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

The template code for implementing your AI agent is provided in the tasks outlined in the following sections.

## 1.1 Using the Simulator

We provide a local game simulator to help you debug, test, and play against your agent. While using the simulator is optional, it is highly recommended as an essential tool for testing and refining your agent’s strategy. Keep in mind that although your agent may function correctly in the local simulator, it may not fully comply with all the limits and requirements of the contest, as the simulator does not enforce every rule or constraint. 

### 1.1.1 Using the CLI Simulator (Recommended)

In this example, we demonstrate how to set up and run the CLI simulator for a Connect 4 game. You'll begin by importing the `GameController` from the `simulator` package and two `HumanAgent` instances to represent the players. The game board is managed using the `ConnectFour` class, which is imported from the `connect_four` module and creates the standard 6x7 grid where the game is played. This setup allows you to simulate a two-player Connect 4 match directly in the terminal. To test your custom AI agent, you can replace one of the `HumanAgent` instances with your `AIAgent`, allowing you to see how your agent performs against human players or other agents.

In each round, your agent will receive a read-only view of the current game board as an observation. Using this state, your agent can compute and decide its next move.

**Note:** The CLI simulator is best run outside of Jupyter Notebook, as it requires command-line interaction for human players.

In [1]:
from simulator import GameController, HumanAgent
from connect_four import ConnectFour

board = ConnectFour()
game = GameController(board=board, agents=[HumanAgent(1), HumanAgent(2)])
# game.run()

### 1.1.2 Using the PyGame Simulator (Optional)

For your convenience, we’ve implemented an optional GUI version of the simulator. To run the PyGame simulator, you’ll need to install the `pygame` package. For a quick and easy setup, we’ve included the installation command for pip below:

```bash
pip install pygame
```

This code snippet is similar to the CLI simulator, but it generates a GUI for interacting with your agent, so it cannot be run within Jupyter Notebook. For example, we used the previously introduced `ZeroAgent`, an agent that always selects the 0th column. You can find this example in the `zero_game.py` file. To see the agent in action and play against it, simply run:

```bash
python zero_game.py
```

Below is a screengrab showing a human player defeating the `ZeroAgent`. The game ends when one of the agents successfully aligns four consecutive discs vertically, horizontally, or diagonally!

![Winning against the ZeroAgent.](./images/zero-agent.png)

## Task 1.1 Make a valid move

Now that you understand the Connect4 game and are familiar with our `ConnectFour` environment, it's time to implement your own agent. Your task is to ensure that your agent makes a valid move within the given time limit (See [Contest Description](#Contest-Description)). The public test cases will only verify whether your agent meets these basic criteria. Once you've passed all test cases, you can proceed to the next two challenges, where you'll see if your agent can outplay two of our agents.

In [ ]:
import random


class AIAgent(object):
    """
    A class representing an agent that plays Connect Four.
    """
    def __init__(self, player_id=1):
        """Initializes the agent with the specified player ID.

        Parameters:
        -----------
        player_id : int
            The ID of the player assigned to this agent (1 or 2).
        """
        self.player_id = player_id
    def make_move(self, state):
        """
        Determines and returns the next move for the agent based on the current game state.

        Parameters:
        -----------
        state : np.ndarray
            A 2D numpy array representing the current, read-only state of the game board. 
            The board contains:
            - 0 for an empty cell,
            - 1 for Player 1's piece,
            - 2 for Player 2's piece.

        Returns:
        --------
        int
            The valid action, ie. a valid column index (col_id) where this agent chooses to drop its piece.
        """
        """ YOUR CODE HERE """
        numCols = state.shape[1]
        validCols = [col for col in range(numCols) if state[0, col] == 0]
        if not validCols:
            raise ValueError("no valid moves")
        
        return random.choice(validCols)
        raise NotImplementedError
        """ YOUR CODE END HERE """

# Test cases
from utils import check_step, actions_to_board

# Test case 1
res1 = check_step(ConnectFour(), 1, AIAgent)
assert(res1 == "Pass")

# Test case 2
res2 = check_step(actions_to_board([0, 0, 0, 0, 0, 0]), 1, AIAgent)
assert(res2 == "Pass")

# Test case 3
res2 = check_step(actions_to_board([4, 3, 4, 5, 5, 1, 4, 4, 5, 5]), 1, AIAgent)
assert(res2 == "Pass")

# Part 2: Contest - Implementing your own agent

## Contest Description

### Grading

This contest will account for $10\%$ of your CS2109S grade, distributed as follows:

- **10\% - Report**: Submission will be done via the "Assessment" section on Coursemology, similar to Lecture Training.
    - The report will be graded based on the appropriate application of any AI/ML techniques.
    - Submission opens after the agent submission deadline: 23:59, 9 November 2024.
    - The specific report format will be announced after the agent submission deadline.
    - The report must be submitted by 23:59, 12 November 2024 (3 days after the agent submission deadline).
- **40\% - Performance against our agents**: Your agent will be tested in a manner similar to the 1v1 Contest, against opponents of varying difficulty levels. The performance against each of the 4 agents will carry equal weight in grading.
    - Baby Agent (Task 2.1)
    - Base Agent (Task 2.2)
    - Hidden Agent 1
    - Hidden Agent 2
- **50\% - 1v1 Contest**: Your agent will face off against other student-submitted agents in a head-to-head competition.
    - The agent you submit for Task 2.2 will be used for the contest:
        - Your agent will play against each other agent in two matches: one where your agent goes first, and one where it goes second.
        - Each match is worth 1 point: 
            - If your agent wins a match, it earns 1 point.
            - If your agent draws, it earns 0.5 points.
        - Your agent total score will be the sum of the scores across all of its matches played.
    - Your grade will be determined by your agent's total score in the contest.
    - To help you assess your agent's performance, we will run a mock 1v1 contest featuring the agents submitted (either Task 2.1 or 2.2) up to that point.
        - Results will be published periodically, beginning after the recess week.

### Rules

You must adhere to the following rules; failure to do so may result in the disqualification of your agent:

1. You are to use any (AI/ML) techniques.
1. You may use any dataset and you may generate more data as necessary:
    1. We suggest using this [UCI - Connect-4](https://archive.ics.uci.edu/dataset/26/connect+4).
1. Limitations:
    1. The size of the submitted code should not exceed 1MB - We will validate this when we run the contest.
    1. Task 2.1
        1. The maximum number of attempts is 20.
        1. Submission will only be available on Coursemology from 16 September 2024 to 13 October 2024.
        1. After 13 October 2024, the attempt limit will be reduced to 1. Any unused attempts will be forfeited.
        1. The submission here will be used to run the mock contest up till 13 October 2024.
    1. Task 2.2
        1. The maximum number of attempts is 20.
        1. Submission will only be available on Coursemology from 13 October 2024 to 9 November 2024.
        1. Your submission here will be used for the contest.
    1. Every of your agent's API calls, must take less than 1 second (as measured on Coursemology). Keep in mind that Coursemology runs slower than local environments, so this time limit may be adjusted when running off-platform.
        1. All of your agent's code should be contained within `__init__` and `make_move`.
        1. If `__init__` takes more than 1 second, your agent will be disqualified.
        1. If `make_move` takes more than 1 second, a random move will be made on its behalf.
1. Your agent must be fully functional and capable of running on Coursemology.
    1. It must work without any additional packages, other than those provided by Coursemology.
    2. It must work without downloading any files/folders or calling external resources.
    3. You may load weights of your models directly within your code. 
1. All work must be completed individually. Any external resources (e.g., datasets) must be properly cited.
1. Your agent must operate fairly and must not engage in any form of cheating or malicious behavior.

## Task 2.1: Defeat the Baby Agent

In this task, your goal is to implement an agent capable of defeating the baby agent. This step helps you validate your agent’s basic functionality and strategy before facing more challenging opponents. Please note that the code submitted here is not your final implementation for the contest.

Available on Coursemology from 16 September 2024 to 13 October 2024. After 13 October 2024, the attempt limit will be reduced to 1. Any unused attempts will be forfeited.

**Important**: This test case may take some time to execute, and you are limited to 20 attempts for this question. Before proceeding, ensure that you paste only your `AIAgent` code here and that you've passed all test cases from the previous question. Additionally, make sure you have thoroughly tested your code locally before running these test cases.

In [ ]:
class AIAgent(object):
    """
    A class representing an agent that plays Connect Four.
    """
    def __init__(self, player_id=1):
        """Initializes the agent with the specified player ID.

        Parameters:
        -----------
        player_id : int
            The ID of the player assigned to this agent (1 or 2).
        """
        self.player_id = player_id
    def make_move(self, state):



        def is_valid_location(board, col):
            return board[0][col] == 0

        def get_valid_locations(board):
            return [col for col in range(board.shape[1]) if is_valid_location(board, col)]

        def get_next_open_row(board, col):
            for row in range(board.shape[0] - 1, -1, -1):
                if board[row][col] == 0:
                    return row
            return None

        def drop_piece(board, row, col, piece):
            board[row][col] = piece

        def winning_move(board, piece):
            ROW_COUNT = board.shape[0]
            COLUMN_COUNT = board.shape[1]

            # Check horizontal locations for win
            for c in range(COLUMN_COUNT - 3):
                for r in range(ROW_COUNT):
                    if (
                        board[r][c] == piece
                        and board[r][c + 1] == piece
                        and board[r][c + 2] == piece
                        and board[r][c + 3] == piece
                    ):
                        return True

            # Check vertical locations for win
            for c in range(COLUMN_COUNT):
                for r in range(ROW_COUNT - 3):
                    if (
                        board[r][c] == piece
                        and board[r + 1][c] == piece
                        and board[r + 2][c] == piece
                        and board[r + 3][c] == piece
                    ):
                        return True

            # Check positively sloped diagonals
            for c in range(COLUMN_COUNT - 3):
                for r in range(ROW_COUNT - 3):
                    if (
                        board[r][c] == piece
                        and board[r + 1][c + 1] == piece
                        and board[r + 2][c + 2] == piece
                        and board[r + 3][c + 3] == piece
                    ):
                        return True

            # Check negatively sloped diagonals
            for c in range(COLUMN_COUNT - 3):
                for r in range(3, ROW_COUNT):
                    if (
                        board[r][c] == piece
                        and board[r - 1][c + 1] == piece
                        and board[r - 2][c + 2] == piece
                        and board[r - 3][c + 3] == piece
                    ):
                        return True

            return False

        def is_terminal_node(board):
            return (
                winning_move(board, self.player_id)
                or winning_move(board, 3 - self.player_id)
                or len(get_valid_locations(board)) == 0
            )

        def evaluate_window(window, piece):
            score = 0
            opp_piece = 3 - piece

            if window.count(piece) == 4:
                score += 100
            elif window.count(piece) == 3 and window.count(0) == 1:
                score += 5
            elif window.count(piece) == 2 and window.count(0) == 2:
                score += 2

            if window.count(opp_piece) == 3 and window.count(0) == 1:
                score -= 4

            return score

        def score_position(board, piece):
            score = 0

            # Score center column
            center_array = [int(i) for i in list(board[:, board.shape[1] // 2])]
            center_count = center_array.count(piece)
            score += center_count * 3

            # Score Horizontal
            for r in range(board.shape[0]):
                row_array = [int(i) for i in list(board[r, :])]
                for c in range(board.shape[1] - 3):
                    window = row_array[c : c + 4]
                    score += evaluate_window(window, piece)

            # Score Vertical
            for c in range(board.shape[1]):
                col_array = [int(i) for i in list(board[:, c])]
                for r in range(board.shape[0] - 3):
                    window = col_array[r : r + 4]
                    score += evaluate_window(window, piece)

            # Score positive sloped diagonal
            for r in range(board.shape[0] - 3):
                for c in range(board.shape[1] - 3):
                    window = [board[r + i][c + i] for i in range(4)]
                    score += evaluate_window(window, piece)

            # Score negative sloped diagonal
            for r in range(board.shape[0] - 3):
                for c in range(board.shape[1] - 3):
                    window = [board[r + 3 - i][c + i] for i in range(4)]
                    score += evaluate_window(window, piece)

            return score

        def minimax(board, depth, alpha, beta, maximizingPlayer):
            valid_locations = get_valid_locations(board)
            is_terminal = is_terminal_node(board)
            if depth == 0 or is_terminal:
                if is_terminal:
                    if winning_move(board, self.player_id):
                        return (None, 100000000000000)
                    elif winning_move(board, 3 - self.player_id):
                        return (None, -10000000000000)
                    else:
                        return (None, 0)
                else:
                    return (None, score_position(board, self.player_id))
            if maximizingPlayer:
                value = -math.inf
                best_col = random.choice(valid_locations)
                for col in valid_locations:
                    row = get_next_open_row(board, col)
                    temp_board = board.copy()
                    drop_piece(temp_board, row, col, self.player_id)
                    new_score = minimax(temp_board, depth - 1, alpha, beta, False)[1]
                    if new_score > value:
                        value = new_score
                        best_col = col
                    alpha = max(alpha, value)
                    if alpha >= beta:
                        break
                return best_col, value
            else:
                value = math.inf
                best_col = random.choice(valid_locations)
                for col in valid_locations:
                    row = get_next_open_row(board, col)
                    temp_board = board.copy()
                    drop_piece(temp_board, row, col, 3 - self.player_id)
                    new_score = minimax(temp_board, depth - 1, alpha, beta, True)[1]
                    if new_score < value:
                        value = new_score
                        best_col = col
                    beta = min(beta, value)
                    if alpha >= beta:
                        break
                return best_col, value

        valid_locations = get_valid_locations(state)
        if not valid_locations:
            raise ValueError("No valid moves")
        col, minimax_score = minimax(state.copy(), 7, -math.inf, math.inf, True)
        if col is None:
            col = random.choice(valid_locations)
        return col
    """ YOUR CODE END HERE """
    

# Test cases
assert(True)
# Upload your code to Coursemology to test it against our agent.

## Task 2.2: Defeat the Base Agent

**The code you submit here will be your final implementation used for the 1v1 contest. Ensure that your agent is capable of competing effectively against the base agent.**

Available on Coursemology from 13 October 2024 to 9 November 2024.

**Important**: This test case may take some time to execute, and you are limited to 20 attempts for this question. Before proceeding, ensure that you paste only your `AIAgent` code here and that you've passed all test cases from the previous question. Additionally, make sure you have thoroughly tested your code locally before running these test cases.

In [ ]:
class AIAgent(object):
    """
    A class representing an agent that plays Connect Four.
    """
    def __init__(self, player_id=1):
        """Initializes the agent with the specified player ID.

        Parameters:
        -----------
        player_id : int
            The ID of the player assigned to this agent (1 or 2).
        """
        pass
    def make_move(self, state):
        """
        Determines and returns the next move for the agent based on the current game state.

        Parameters:
        -----------
        state : np.ndarray
            A 2D numpy array representing the current, read-only state of the game board. 
            The board contains:
            - 0 for an empty cell,
            - 1 for Player 1's piece,
            - 2 for Player 2's piece.

        Returns:
        --------
        int
            The valid action, ie. a valid column index (col_id) where this agent chooses to drop its piece.
        """
        """ YOUR CODE HERE """
        raise NotImplementedError
        """ YOUR CODE END HERE """

# Test cases
assert(True)
# Upload your code to Coursemology to test it against our agent.

# Submission

Once you're ready, please submit your work to Coursemology by copying the relevant code snippets into the corresponding text boxes and saving After saving, you'll still have the opportunity to make changes to your submission.

### Additional Notes:
- Please ensure you carefully read the detailed submission instructions provided in the Coursemology question description.
- For Task 1.1, Task 2.1 and Task 2.2, you will need to paste the same code. Only Task 2.2 will be used for the final contest.
- Each public test case may take up some time to complete, please be patient.

Once you're satisfied with your submission, click 'Finalize submission.' Be aware that after finalizing, your submission will be locked for grading and cannot be changed. If you need to undo this action, you will need to contact your assigned tutor for assistance. Please **do not finalize** your submission until you are certain you want to submit it for grading.